### PR TITLE
fix: overlay position dislocation when resize the window

### LINKED ISSUE #1: Bug: overlay position dislocation when I resizing the window
image

Maybe the mask effect should be cleared here when the screen size changes.

The same bug will be generated when scrolling.

### PR DESCRIPTION
**Pull request by zhangmo8**
I tried to using the entire document directly to the `targetNode`, But the effect is not ideal.

close #1

### CODE REVIEW

File: src/Overlay.svelte [hunk 1]
```diff
@@ -67,16 +67,20 @@
         toggleCombo && document.body.addEventListener('keydown', onKeydown)
         toggleEventListener()
     })
+    
     function toggleEventListener() {
         const listener = enabled ? document.body.addEventListener : document.body.removeEventListener
+        listener?.('resize', resetLinkParams)
```
Comment (baiwusanyu-c) [inline src/Overlay.svelte:78]:
```suggestion
        listener?.('resize', resetLinkParams)
        listener?.('scroll', resetLinkParams)
```

**Comment by baiwusanyu-c** [comment]
I think it is enough to reset the overlay when the size changes and the scroll bar, there is no need to consider too complicated

**Comment by zhangmo8** [comment]
> 

Yep. I think so.

**Review by baiwusanyu-c — APPROVED** [review]
